list = [10,20,30,40,50,60]
print(list)
print(type(list))
print("Accessing the list Elements using positive index: ")
print(list[0])
print(list[1])
print(list[2])
print(list[3])
print(list[4])
print(list[5])
print("Accessing the list Elements using negative index:")
print(list[-1])
print(list[-2])
print(list[-3])
print(list[-4])
print(list[-5])
print(list[0])